
import type { Client, Artist, Event, Purchase } from './types';

export const clients: Client[] = [
  {
    id: 'cli-1',
    name: 'Espaço Cultural Harmonia',
    email: 'contato@harmonia.com',
    phone: '(11) 98765-4321',
    responsavel: 'Maria Silva',
    local: 'Rua das Flores, 123, São Paulo, SP',
    instagram: '@espacoharmonia',
    userId: 'user123',
  },
  {
    id: 'cli-2',
    name: 'Bar do Rock',
    email: 'bdr@email.com',
    phone: '(21) 99999-8888',
    responsavel: 'João Pereira',
    local: 'Avenida do Som, 456, Rio de Janeiro, RJ',
    instagram: '@bardorock',
    userId: 'user123',
  },
  {
    id: 'cli-3',
    name: 'Casamento Ana e Bruno',
    email: 'ana.bruno@casamento.com',
    phone: '(31) 91234-5678',
    responsavel: 'Ana Souza',
    local: 'Sítio Recanto Feliz, s/n, Belo Horizonte, MG',
    userId: 'user123',
  },
];

export const artists: Artist[] = [
  {
    id: 'art-1',
    name: 'Os Reis do Sertanejo',
    genre: 'Sertanejo',
    performanceDetails: 'Duo sertanejo com repertório variado.',
    instagram: '@reisdosertanejo',
    phone: '(11) 98888-7777',
    email: 'contato@reisdosertanejo.com',
    userId: 'user123',
  },
  {
    id: 'art-2',
    name: 'Banda Rock N’ Rollers',
    genre: 'Rock Clássico',
    performanceDetails: 'Banda completa com clássicos do rock dos anos 80 e 90.',
    instagram: '@rocknrollers',
    phone: '(21) 97777-6666',
    email: 'contato@rocknrollers.com',
    userId: 'user123',
  },
  {
    id: 'art-3',
    name: 'DJ Eletrônico',
    genre: 'Eletrônica',
    performanceDetails: 'DJ com foco em música eletrônica e remixes.',
    instagram: '@djeletronico',
    phone: '(41) 96666-5555',
    email: 'contato@djeletronico.com',
    userId: 'user123',
  },
];

export const events: Event[] = [
    {
        id: 'evt-1',
        clientId: 'cli-1',
        artistIds: ['art-1'],
        date: '2024-08-15',
        time: '20:00',
        local: 'Espaço Cultural Harmonia',
        payment: 2500,
        status: 'Confirmado',
        paymentStatus: 'Pago',
        userId: 'user123',
        hasSound: true,
    },
    {
        id: 'evt-2',
        clientId: 'cli-2',
        artistIds: ['art-2'],
        date: '2024-08-20',
        time: '22:00',
        local: 'Bar do Rock',
        payment: 1800,
        status: 'Pendente',
        paymentStatus: 'Não Pago',
        userId: 'user123',
        hasSound: false,
    },
    {
        id: 'evt-3',
        clientId: 'cli-3',
        artistIds: ['art-1', 'art-3'],
        date: '2024-09-01',
        time: '18:00',
        local: 'Sítio Recanto Feliz',
        payment: 4500,
        status: 'Confirmado',
        paymentStatus: 'Não Pago',
        userId: 'user123',
        hasSound: true,
    },
];

export const purchases: Purchase[] = [
  {
    id: 'pur-1',
    description: 'Cabo de Guitarra P10',
    recipient: 'Loja Som Total',
    amount: 150,
    date: '2024-07-20',
    paymentMethod: 'Cartão de Crédito',
    installments: 1,
    userId: 'user123',
    details: 'Cabo Fender 3m',
    status: 'Pago',
  },
  {
    id: 'pur-2',
    description: 'Pagamento cachê',
    artistId: 'art-2',
    amount: 800,
    date: '2024-07-22',
    paymentMethod: 'PIX',
    pixKey: '21977776666',
    userId: 'user123',
    status: 'Pago',
  },
   {
    id: 'pur-3',
    description: 'Adiantamento cachê',
    artistId: 'art-1',
    amount: 500,
    date: '2024-08-01',
    paymentMethod: 'PIX',
    pixKey: '11988887777',
    userId: 'user123',
    status: 'Não Pago',
  },
];
